# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "lastfm"
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["youpy"]
  s.date = "2011-12-03"
  s.description = "A ruby interface for Last.fm web services version 2.0"
  s.email = "youpy@buycheapviagraonlinenow.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lastfm.gemspec",
    "lib/lastfm.rb",
    "lib/lastfm/method_category/artist.rb",
    "lib/lastfm/method_category/auth.rb",
    "lib/lastfm/method_category/base.rb",
    "lib/lastfm/method_category/geo.rb",
    "lib/lastfm/method_category/library.rb",
    "lib/lastfm/method_category/track.rb",
    "lib/lastfm/method_category/user.rb",
    "lib/lastfm/response.rb",
    "lib/lastfm/util.rb",
    "spec/fixtures/artist_get_events.xml",
    "spec/fixtures/geo_get_events.xml",
    "spec/fixtures/library_get_artists.xml",
    "spec/fixtures/ng.xml",
    "spec/fixtures/ok.xml",
    "spec/fixtures/track_get_correction.xml",
    "spec/fixtures/track_get_info.xml",
    "spec/fixtures/track_get_info_force_array.xml",
    "spec/fixtures/track_get_similar.xml",
    "spec/fixtures/track_get_tags.xml",
    "spec/fixtures/track_get_top_fans.xml",
    "spec/fixtures/track_get_top_tags.xml",
    "spec/fixtures/track_search.xml",
    "spec/fixtures/user_get_friends.xml",
    "spec/fixtures/user_get_info.xml",
    "spec/fixtures/user_get_neighbours.xml",
    "spec/fixtures/user_get_recent_tracks.xml",
    "spec/lastfm_spec.rb",
    "spec/method_category_spec.rb",
    "spec/response_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/youpy/ruby-lastfm"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Ruby interface for Last.fm Web Services"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.3"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<xml-simple>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 3.0.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<xml-simple>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 3.0.3"])
  end
end

